name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 🔹 Checkout repo
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true
          lfs: false

      # 🔹 Setup Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 🔹 Install all workspace dependencies at root (includes devDependencies)
      - name: Install dependencies
        run: npm install

      # 🔹 Build only the frontend (prebuilt)
      - name: Build frontend
        run: npm run build --prefix frontend

      # 🔹 Deploy prebuilt frontend and source API
      - name: Deploy Prebuilt Artifacts
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_TREE_05189EC03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/dist"  # prebuilt frontend folder
          api_location: "api"             # deploy source API folder for function detection
          output_location: ""            # disables extra build step

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_TREE_05189EC03 }}
          action: "close"
