name: Manual Playwright Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
      base_url:
        description: 'Base URL for Playwright tests'
        required: true
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./frontend
        run: npx playwright test --reporter=json --reporter=html --output=playwright-report
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}

      - name: Report Playwright test summary
        if: always()
        uses: daun/playwright-report-summary@v3
        with:
          report-file: ./frontend/playwright-report/test-results.json
      
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: ./frontend/playwright-report/html
      
      - name: Add link to HTML report in Checks summary
        if: always()
        run: |
          echo "## [Playwright HTML Report](https://github.com/${GITHUB_REPOSITORY}/suites/${GITHUB_RUN_ID}/artifacts)" >> $GITHUB_STEP_SUMMARY
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            ./frontend/playwright-report/test-results.json

